import CashierTemplat from "@/components/adminTemplate"
import MenuList from "../menuList"

export const metadata = {
    title: 'Pesan barang | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplat title="Pesan barang" id="pesan_barang" menuList={MenuList}>
            {children}
        </CashierTemplat>
    )
}
export default RootLayout